/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.truba;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aditya Sharma
 */
public class PowerOptions extends javax.swing.JFrame {

    /**
     * Creates new form PowerOptions
     */
    public PowerOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShut = new javax.swing.JButton();
        btnRest = new javax.swing.JButton();
        btnHiber = new javax.swing.JButton();
        btnShut60 = new javax.swing.JButton();
        btnRest60 = new javax.swing.JButton();
        btnShutNoMsg = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        spinTimeSec = new javax.swing.JSpinner();
        spinTimeHour = new javax.swing.JSpinner();
        spinTimeMin = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        btnShut.setText("Shutdown");
        btnShut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShutActionPerformed(evt);
            }
        });

        btnRest.setText("Restart");
        btnRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestActionPerformed(evt);
            }
        });

        btnHiber.setText("Hibernate");
        btnHiber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHiberActionPerformed(evt);
            }
        });

        btnShut60.setText("Shutdown After 60 sec");
        btnShut60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShut60ActionPerformed(evt);
            }
        });

        btnRest60.setText("Restart After 60 sec");
        btnRest60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRest60ActionPerformed(evt);
            }
        });

        btnShutNoMsg.setText("Shutdown without message");
        btnShutNoMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShutNoMsgActionPerformed(evt);
            }
        });

        btnClose.setText("go back");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        spinTimeSec.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 10));
        spinTimeSec.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinTimeSecStateChanged(evt);
            }
        });

        spinTimeHour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        spinTimeMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnShut60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRest)
                            .addComponent(btnRest60))
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHiber, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(btnShutNoMsg)
                            .addComponent(btnShut))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spinTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(spinTimeMin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(spinTimeSec, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnRest)
                        .addGap(18, 18, 18)
                        .addComponent(btnRest60)
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinTimeSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinTimeMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShut)
                        .addGap(26, 26, 26)
                        .addComponent(btnShut60)
                        .addGap(33, 33, 33)
                        .addComponent(btnShutNoMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(btnHiber)
                        .addGap(85, 85, 85)
                        .addComponent(btnClose)
                        .addGap(70, 70, 70))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShutActionPerformed
        // TODO add your handling code here:
        Runtime r=Runtime.getRuntime();
        try {
            r.exec("shutdown -s");
        } catch (IOException ex) {
            Logger.getLogger(PowerOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnShutActionPerformed

    private void btnShutNoMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShutNoMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShutNoMsgActionPerformed
 private void spinTimeSec(java.awt.event.ActionEvent evt) {   
     
 }
    private void btnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestActionPerformed
        // TODO add your handling code here:
         Runtime r=Runtime.getRuntime();

 

        try {
            // Restart system
            r.exec("shutdown -r");
        } catch (IOException ex) {
            Logger.getLogger(PowerOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRestActionPerformed

    private void btnHiberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHiberActionPerformed
        // TODO add your handling code here:
        Runtime r=Runtime.getRuntime();
        try {
            r.exec("shutdown -h");
        } catch (IOException ex) {
            Logger.getLogger(PowerOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHiberActionPerformed

    private void btnShut60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShut60ActionPerformed
        // TODO add your handling code here:
        
        Runtime r=Runtime.getRuntime();

 
        try {
            r.exec("shutdown -s -t 60");
        } catch (IOException ex) {
            Logger.getLogger(PowerOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnShut60ActionPerformed

    private void btnRest60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRest60ActionPerformed
        // TODO add your handling code here:
        
        Runtime r=Runtime.getRuntime();

 
        try {
            r.exec("shutdown -r -t 60");
        } catch (IOException ex) {
            Logger.getLogger(PowerOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRest60ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        //InterfaceDisplay ab = new InterfaceDisplay();
        //ab.setVisible(true);
        PowerOptions.this.dispose();
        InterfaceDisplay idd = new InterfaceDisplay();
        idd.setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formWindowLostFocus

    private void spinTimeSecStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinTimeSecStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spinTimeSecStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s = spinTimeSec.getValue().toString();
        String m = spinTimeMin.getValue().toString();
        String h = spinTimeHour.getValue().toString();
        //s = s+m+h;
         int time = 0;
        int hour = Integer.parseInt(h);
        int sec = Integer.parseInt(s);
        int min = Integer.parseInt(m);
        System.out.println(sec);
            System.out.println(min);
            System.out.println(hour);
            
            System.out.println(time);
        if(min>=0||hour>=0){time = hour*60*60+min*60+sec;
            System.out.println(sec);
            System.out.println(min);
            System.out.println(hour);
            
            System.out.println(time);
        }
        Runtime r=Runtime.getRuntime();
        String pass = "shutdown -s -t "+time;
 
        try {
            r.exec(pass);
        } catch (IOException ex) {
            Logger.getLogger(PowerOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PowerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PowerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PowerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PowerOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHiber;
    private javax.swing.JButton btnRest;
    private javax.swing.JButton btnRest60;
    private javax.swing.JButton btnShut;
    private javax.swing.JButton btnShut60;
    private javax.swing.JButton btnShutNoMsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JSpinner spinTimeHour;
    private javax.swing.JSpinner spinTimeMin;
    private javax.swing.JSpinner spinTimeSec;
    // End of variables declaration//GEN-END:variables
}
